<?xml version="1.0" encoding="utf-8"?>
<Database Name="Database" Class="DataBaseDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CommonRoom" Member="CommonRooms">
    <Type Name="CommonRoom">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Msg" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="MsgDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.One2One" Member="One2Ones">
    <Type Name="One2One">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SenderId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ReceiverId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsAcceptedS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAcceptedR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="onlinetimeS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="onlinetimeR" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.One2OneData" Member="One2OneDatas">
    <Type Name="One2OneData">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="One2OneId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Msg" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="MsgDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SenderId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserData" Member="UserDatas">
    <Type Name="UserData">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StatusValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="SecurityQuestion" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BDate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BMonth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Byear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GenderIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="onlinetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>