#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class DataBaseDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCommonRoom(CommonRoom instance);
  partial void UpdateCommonRoom(CommonRoom instance);
  partial void DeleteCommonRoom(CommonRoom instance);
  partial void InsertOne2One(One2One instance);
  partial void UpdateOne2One(One2One instance);
  partial void DeleteOne2One(One2One instance);
  partial void InsertOne2OneData(One2OneData instance);
  partial void UpdateOne2OneData(One2OneData instance);
  partial void DeleteOne2OneData(One2OneData instance);
  partial void InsertUserData(UserData instance);
  partial void UpdateUserData(UserData instance);
  partial void DeleteUserData(UserData instance);
  #endregion
	
	public DataBaseDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataBaseDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataBaseDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataBaseDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataBaseDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<CommonRoom> CommonRooms
	{
		get
		{
			return this.GetTable<CommonRoom>();
		}
	}
	
	public System.Data.Linq.Table<One2One> One2Ones
	{
		get
		{
			return this.GetTable<One2One>();
		}
	}
	
	public System.Data.Linq.Table<One2OneData> One2OneDatas
	{
		get
		{
			return this.GetTable<One2OneData>();
		}
	}
	
	public System.Data.Linq.Table<UserData> UserDatas
	{
		get
		{
			return this.GetTable<UserData>();
		}
	}
}

[Table(Name="dbo.CommonRoom")]
public partial class CommonRoom : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _UserId;
	
	private string _Msg;
	
	private System.DateTime _MsgDT;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnMsgChanging(string value);
    partial void OnMsgChanged();
    partial void OnMsgDTChanging(System.DateTime value);
    partial void OnMsgDTChanged();
    #endregion
	
	public CommonRoom()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_UserId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[Column(Storage="_Msg", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string Msg
	{
		get
		{
			return this._Msg;
		}
		set
		{
			if ((this._Msg != value))
			{
				this.OnMsgChanging(value);
				this.SendPropertyChanging();
				this._Msg = value;
				this.SendPropertyChanged("Msg");
				this.OnMsgChanged();
			}
		}
	}
	
	[Column(Storage="_MsgDT", DbType="DateTime NOT NULL")]
	public System.DateTime MsgDT
	{
		get
		{
			return this._MsgDT;
		}
		set
		{
			if ((this._MsgDT != value))
			{
				this.OnMsgDTChanging(value);
				this.SendPropertyChanging();
				this._MsgDT = value;
				this.SendPropertyChanged("MsgDT");
				this.OnMsgDTChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.One2One")]
public partial class One2One : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _SenderId;
	
	private string _ReceiverId;
	
	private System.DateTime _DT;
	
	private int _IsAcceptedS;
	
	private int _IsAcceptedR;
	
	private System.Nullable<System.DateTime> _onlinetimeS;
	
	private System.Nullable<System.DateTime> _onlinetimeR;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSenderIdChanging(string value);
    partial void OnSenderIdChanged();
    partial void OnReceiverIdChanging(string value);
    partial void OnReceiverIdChanged();
    partial void OnDTChanging(System.DateTime value);
    partial void OnDTChanged();
    partial void OnIsAcceptedSChanging(int value);
    partial void OnIsAcceptedSChanged();
    partial void OnIsAcceptedRChanging(int value);
    partial void OnIsAcceptedRChanged();
    partial void OnonlinetimeSChanging(System.Nullable<System.DateTime> value);
    partial void OnonlinetimeSChanged();
    partial void OnonlinetimeRChanging(System.Nullable<System.DateTime> value);
    partial void OnonlinetimeRChanged();
    #endregion
	
	public One2One()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_SenderId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string SenderId
	{
		get
		{
			return this._SenderId;
		}
		set
		{
			if ((this._SenderId != value))
			{
				this.OnSenderIdChanging(value);
				this.SendPropertyChanging();
				this._SenderId = value;
				this.SendPropertyChanged("SenderId");
				this.OnSenderIdChanged();
			}
		}
	}
	
	[Column(Storage="_ReceiverId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string ReceiverId
	{
		get
		{
			return this._ReceiverId;
		}
		set
		{
			if ((this._ReceiverId != value))
			{
				this.OnReceiverIdChanging(value);
				this.SendPropertyChanging();
				this._ReceiverId = value;
				this.SendPropertyChanged("ReceiverId");
				this.OnReceiverIdChanged();
			}
		}
	}
	
	[Column(Storage="_DT", DbType="DateTime NOT NULL")]
	public System.DateTime DT
	{
		get
		{
			return this._DT;
		}
		set
		{
			if ((this._DT != value))
			{
				this.OnDTChanging(value);
				this.SendPropertyChanging();
				this._DT = value;
				this.SendPropertyChanged("DT");
				this.OnDTChanged();
			}
		}
	}
	
	[Column(Storage="_IsAcceptedS", DbType="Int NOT NULL")]
	public int IsAcceptedS
	{
		get
		{
			return this._IsAcceptedS;
		}
		set
		{
			if ((this._IsAcceptedS != value))
			{
				this.OnIsAcceptedSChanging(value);
				this.SendPropertyChanging();
				this._IsAcceptedS = value;
				this.SendPropertyChanged("IsAcceptedS");
				this.OnIsAcceptedSChanged();
			}
		}
	}
	
	[Column(Storage="_IsAcceptedR", DbType="Int NOT NULL")]
	public int IsAcceptedR
	{
		get
		{
			return this._IsAcceptedR;
		}
		set
		{
			if ((this._IsAcceptedR != value))
			{
				this.OnIsAcceptedRChanging(value);
				this.SendPropertyChanging();
				this._IsAcceptedR = value;
				this.SendPropertyChanged("IsAcceptedR");
				this.OnIsAcceptedRChanged();
			}
		}
	}
	
	[Column(Storage="_onlinetimeS", DbType="DateTime")]
	public System.Nullable<System.DateTime> onlinetimeS
	{
		get
		{
			return this._onlinetimeS;
		}
		set
		{
			if ((this._onlinetimeS != value))
			{
				this.OnonlinetimeSChanging(value);
				this.SendPropertyChanging();
				this._onlinetimeS = value;
				this.SendPropertyChanged("onlinetimeS");
				this.OnonlinetimeSChanged();
			}
		}
	}
	
	[Column(Storage="_onlinetimeR", DbType="DateTime")]
	public System.Nullable<System.DateTime> onlinetimeR
	{
		get
		{
			return this._onlinetimeR;
		}
		set
		{
			if ((this._onlinetimeR != value))
			{
				this.OnonlinetimeRChanging(value);
				this.SendPropertyChanging();
				this._onlinetimeR = value;
				this.SendPropertyChanged("onlinetimeR");
				this.OnonlinetimeRChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.One2OneData")]
public partial class One2OneData : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private int _One2OneId;
	
	private string _Msg;
	
	private System.DateTime _MsgDT;
	
	private string _SenderId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOne2OneIdChanging(int value);
    partial void OnOne2OneIdChanged();
    partial void OnMsgChanging(string value);
    partial void OnMsgChanged();
    partial void OnMsgDTChanging(System.DateTime value);
    partial void OnMsgDTChanged();
    partial void OnSenderIdChanging(string value);
    partial void OnSenderIdChanged();
    #endregion
	
	public One2OneData()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_One2OneId", DbType="Int NOT NULL")]
	public int One2OneId
	{
		get
		{
			return this._One2OneId;
		}
		set
		{
			if ((this._One2OneId != value))
			{
				this.OnOne2OneIdChanging(value);
				this.SendPropertyChanging();
				this._One2OneId = value;
				this.SendPropertyChanged("One2OneId");
				this.OnOne2OneIdChanged();
			}
		}
	}
	
	[Column(Storage="_Msg", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string Msg
	{
		get
		{
			return this._Msg;
		}
		set
		{
			if ((this._Msg != value))
			{
				this.OnMsgChanging(value);
				this.SendPropertyChanging();
				this._Msg = value;
				this.SendPropertyChanged("Msg");
				this.OnMsgChanged();
			}
		}
	}
	
	[Column(Storage="_MsgDT", DbType="DateTime NOT NULL")]
	public System.DateTime MsgDT
	{
		get
		{
			return this._MsgDT;
		}
		set
		{
			if ((this._MsgDT != value))
			{
				this.OnMsgDTChanging(value);
				this.SendPropertyChanging();
				this._MsgDT = value;
				this.SendPropertyChanged("MsgDT");
				this.OnMsgDTChanged();
			}
		}
	}
	
	[Column(Storage="_SenderId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string SenderId
	{
		get
		{
			return this._SenderId;
		}
		set
		{
			if ((this._SenderId != value))
			{
				this.OnSenderIdChanging(value);
				this.SendPropertyChanging();
				this._SenderId = value;
				this.SendPropertyChanged("SenderId");
				this.OnSenderIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.UserData")]
public partial class UserData : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _FirstName;
	
	private string _LastName;
	
	private string _UserId;
	
	private string _Password;
	
	private int _StatusValue;
	
	private string _Birthday;
	
	private string _Gender;
	
	private string _Country;
	
	private string _SecurityQuestion;
	
	private string _Answer;
	
	private int _BDate;
	
	private int _BMonth;
	
	private int _Byear;
	
	private int _CountryIndex;
	
	private int _GenderIndex;
	
	private System.Nullable<System.DateTime> _onlinetime;
	
	private string _StatusName;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnStatusValueChanging(int value);
    partial void OnStatusValueChanged();
    partial void OnBirthdayChanging(string value);
    partial void OnBirthdayChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnSecurityQuestionChanging(string value);
    partial void OnSecurityQuestionChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    partial void OnBDateChanging(int value);
    partial void OnBDateChanged();
    partial void OnBMonthChanging(int value);
    partial void OnBMonthChanged();
    partial void OnByearChanging(int value);
    partial void OnByearChanged();
    partial void OnCountryIndexChanging(int value);
    partial void OnCountryIndexChanged();
    partial void OnGenderIndexChanging(int value);
    partial void OnGenderIndexChanged();
    partial void OnonlinetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnonlinetimeChanged();
    partial void OnStatusNameChanging(string value);
    partial void OnStatusNameChanged();
    #endregion
	
	public UserData()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[Column(Storage="_FirstName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this.OnFirstNameChanging(value);
				this.SendPropertyChanging();
				this._FirstName = value;
				this.SendPropertyChanged("FirstName");
				this.OnFirstNameChanged();
			}
		}
	}
	
	[Column(Storage="_LastName", DbType="VarChar(20)")]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this.OnLastNameChanging(value);
				this.SendPropertyChanging();
				this._LastName = value;
				this.SendPropertyChanged("LastName");
				this.OnLastNameChanged();
			}
		}
	}
	
	[Column(Storage="_UserId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[Column(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[Column(Storage="_StatusValue", DbType="Int NOT NULL")]
	public int StatusValue
	{
		get
		{
			return this._StatusValue;
		}
		set
		{
			if ((this._StatusValue != value))
			{
				this.OnStatusValueChanging(value);
				this.SendPropertyChanging();
				this._StatusValue = value;
				this.SendPropertyChanged("StatusValue");
				this.OnStatusValueChanged();
			}
		}
	}
	
	[Column(Storage="_Birthday", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Birthday
	{
		get
		{
			return this._Birthday;
		}
		set
		{
			if ((this._Birthday != value))
			{
				this.OnBirthdayChanging(value);
				this.SendPropertyChanging();
				this._Birthday = value;
				this.SendPropertyChanged("Birthday");
				this.OnBirthdayChanged();
			}
		}
	}
	
	[Column(Storage="_Gender", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[Column(Storage="_Country", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this.OnCountryChanging(value);
				this.SendPropertyChanging();
				this._Country = value;
				this.SendPropertyChanged("Country");
				this.OnCountryChanged();
			}
		}
	}
	
	[Column(Storage="_SecurityQuestion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string SecurityQuestion
	{
		get
		{
			return this._SecurityQuestion;
		}
		set
		{
			if ((this._SecurityQuestion != value))
			{
				this.OnSecurityQuestionChanging(value);
				this.SendPropertyChanging();
				this._SecurityQuestion = value;
				this.SendPropertyChanged("SecurityQuestion");
				this.OnSecurityQuestionChanged();
			}
		}
	}
	
	[Column(Storage="_Answer", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Answer
	{
		get
		{
			return this._Answer;
		}
		set
		{
			if ((this._Answer != value))
			{
				this.OnAnswerChanging(value);
				this.SendPropertyChanging();
				this._Answer = value;
				this.SendPropertyChanged("Answer");
				this.OnAnswerChanged();
			}
		}
	}
	
	[Column(Storage="_BDate", DbType="Int NOT NULL")]
	public int BDate
	{
		get
		{
			return this._BDate;
		}
		set
		{
			if ((this._BDate != value))
			{
				this.OnBDateChanging(value);
				this.SendPropertyChanging();
				this._BDate = value;
				this.SendPropertyChanged("BDate");
				this.OnBDateChanged();
			}
		}
	}
	
	[Column(Storage="_BMonth", DbType="Int NOT NULL")]
	public int BMonth
	{
		get
		{
			return this._BMonth;
		}
		set
		{
			if ((this._BMonth != value))
			{
				this.OnBMonthChanging(value);
				this.SendPropertyChanging();
				this._BMonth = value;
				this.SendPropertyChanged("BMonth");
				this.OnBMonthChanged();
			}
		}
	}
	
	[Column(Storage="_Byear", DbType="Int NOT NULL")]
	public int Byear
	{
		get
		{
			return this._Byear;
		}
		set
		{
			if ((this._Byear != value))
			{
				this.OnByearChanging(value);
				this.SendPropertyChanging();
				this._Byear = value;
				this.SendPropertyChanged("Byear");
				this.OnByearChanged();
			}
		}
	}
	
	[Column(Storage="_CountryIndex", DbType="Int NOT NULL")]
	public int CountryIndex
	{
		get
		{
			return this._CountryIndex;
		}
		set
		{
			if ((this._CountryIndex != value))
			{
				this.OnCountryIndexChanging(value);
				this.SendPropertyChanging();
				this._CountryIndex = value;
				this.SendPropertyChanged("CountryIndex");
				this.OnCountryIndexChanged();
			}
		}
	}
	
	[Column(Storage="_GenderIndex", DbType="Int NOT NULL")]
	public int GenderIndex
	{
		get
		{
			return this._GenderIndex;
		}
		set
		{
			if ((this._GenderIndex != value))
			{
				this.OnGenderIndexChanging(value);
				this.SendPropertyChanging();
				this._GenderIndex = value;
				this.SendPropertyChanged("GenderIndex");
				this.OnGenderIndexChanged();
			}
		}
	}
	
	[Column(Storage="_onlinetime", DbType="DateTime")]
	public System.Nullable<System.DateTime> onlinetime
	{
		get
		{
			return this._onlinetime;
		}
		set
		{
			if ((this._onlinetime != value))
			{
				this.OnonlinetimeChanging(value);
				this.SendPropertyChanging();
				this._onlinetime = value;
				this.SendPropertyChanged("onlinetime");
				this.OnonlinetimeChanged();
			}
		}
	}
	
	[Column(Storage="_StatusName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string StatusName
	{
		get
		{
			return this._StatusName;
		}
		set
		{
			if ((this._StatusName != value))
			{
				this.OnStatusNameChanging(value);
				this.SendPropertyChanging();
				this._StatusName = value;
				this.SendPropertyChanged("StatusName");
				this.OnStatusNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
